"""first migration

Revision ID: 5c4043a139b6
Revises: 
Create Date: 2025-02-23 00:50:29.848798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4043a139b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('lastName', sa.String(length=150), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(length=500), nullable=False),
                    sa.Column('roleId', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['roleId'], ['roles.id']),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )

    op.create_table('models',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('version', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=True),
                    sa.Column('modelType', sa.String(length=100), nullable=False),
                    sa.Column('createdOn', sa.DateTime(), nullable=False),
                    sa.Column('updatedOn', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', 'version')
                    )

    op.create_table('datasets',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('datasetType', sa.String(length=20), nullable=False),
                    sa.Column('s3Path', sa.String(length=500), nullable=True),
                    sa.Column('createdBy', sa.Integer(), nullable=False),
                    sa.Column('createdOn', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['createdBy'], ['users.id']),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )

    op.create_table('inferences',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userId', sa.Integer(), nullable=False),
                    sa.Column('modelId', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.Column('baseImageUrl', sa.String(), nullable=False),
                    sa.Column('generatedImageUrl', sa.String(), nullable=True),
                    sa.Column('createdOn', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['userId'], ['users.id']),
                    sa.ForeignKeyConstraint(['modelId'], ['models.id']),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('model_datasets',
                    sa.Column('modelId', sa.Integer(), nullable=False),
                    sa.Column('datasetId', sa.Integer(), nullable=False),
                    sa.Column('usageType', sa.String(length=20), nullable=False),
                    sa.Column('createdOn', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['modelId'], ['models.id']),
                    sa.ForeignKeyConstraint(['datasetId'], ['datasets.id']),
                    sa.PrimaryKeyConstraint('modelId', 'datasetId')
                    )

    op.create_table('audit_logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userId', sa.Integer(), nullable=True),
                    sa.Column('action', sa.String(length=100), nullable=False),
                    sa.Column('entityType', sa.String(length=50), nullable=False),
                    sa.Column('entityId', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['userId'], ['users.id']),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inferences')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
