# syntax=docker/dockerfile:1.4
FROM python:3.11

WORKDIR /app

# Install OS dependencies
RUN apt-get update -y
RUN apt-get install -y gcc libpq-dev

# Install app dependencies
COPY requirements.txt /app
RUN pip3 install -r requirements.txt

# Export some env vars flask needs
ENV FLASK_APP=src.app:create_app
ENV FLASK_ENV=development

# Run migrations & start flask app
ENTRYPOINT ["sh", "-c", "flask db upgrade && python3 run.py"]
